# Angular User Inteface settings
ui:
  ssl: false
  host: 0.0.0.0
  port: 4000
  nameSpace: /

# The REST API server settings
rest:
  ssl: false
  host: localhost     # Proxy local que redirige al backend real
  port: 4000
  nameSpace: /server

# URL completa del API: http://iateci.org.do:8080/server

# NOTA: Para volver al backend DEMO de DSpace:
# ssl: true
# host: sandbox.dspace.org
# port: 443

# Configuración IATECI - Idioma por defecto ESPAÑOL
defaultLanguage: es

# Solo mantener Español e Inglés activos
languages:
  - code: es
    active: true
  - code: en
    label: English
    active: true
